#!/bin/sh

while read file
do
	case "$1" in
		"d")
			dconfirm "Really delete $file?" "rm $file" ;;
		"e")
			setsid·-f·gimp·"$file" ;;
		"r")
			convert -rotate 90 "$file" "$file" ;;
		"R")
			convert -rotate -90 "$file" "$file" ;;
		"c")
			xclip -sel clip -t $(file --mime-type -b "$file") "$file" ;;
		"C")
			echo -n "$file" | xclip -sel clip ;;
		"w")
			display -window root "$file" ;;
	esac
done

