#!/bin/sh

if [ -e "$FIFO_UEBERZUG" ]; then
	if [ "$1" = "draw" ]; then
		printf "{\"action\":\"add\",\"identifier\":\"preview\",\"x\":\"$2\",\"y\":\"$3\",\"width\":\"$4\",\"height\":\"$5\",\"path\":\"${PWD}/$6\"}\n" > "$FIFO_UEBERZUG"
	else
		printf "{\"action\":\"remove\",\"identifier\":\"preview\"}\n" > "$FIFO_UEBERZUG"
	fi
fi

