#!/bin/sh

export FIFO_UEBERZUG="/tmp/vifm-ueberzug-${PPID}"

cleanup() {
	rm "$FIFO_UEBERZUG" 2>/dev/null
	pkill -P $$ 2>/dev/null
}

cleanup

mkfifo "$FIFO_UEBERZUG"
trap cleanup EXIT
tail --follow "$FIFO_UEBERZUG" | ueberzug layer -sp json &

vifm "$@"
cleanup

