#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a st-256color -o private=on locked=on
bspc rule -a mpv state=floating focus=off

